workflows:
  ios-unsigned-build:
    name: iOS Unsigned Build (for AS)
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    scripts:
      - name: Flutter pub get
        script: flutter packages pub get
        
      - name: Build Unsigned .app
        script: |
          # 1. まず署名なしでビルド
          flutter build ios --release --no-codesign --no-pub
          
      - name: Payload into .ipa
        script: |
          # 2. .appを手動で.ipaにパッケージングする
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r Runner.ipa Payload
          # 作成場所をCodemagicが認識できる場所に移動
          mv Runner.ipa $CM_BUILD_DIR/Runner.ipa

    artifacts:
      - Runner.ipa