workflows:
  ios-devsigned-build:
    name: iOS PortableSec Build
    integrations:
      app_store_connect: "AppStoreConnect 0219"
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
# 2. 自動コード署名（Automatic Code Signing）の設定
      ios_signing:
        #distribution_type: app_store # TestFlightの場合はapp_storeを指定
        #bundle_identifier: com.poc.iosnfc # あなたのアプリのBundle ID
        provisioning_profiles:
          - portableSec_profile
      flutter: stable
      xcode: latest
      # なくても動くが、バージョン固定のために推奨
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    scripts:
      - name: Flutter pub get
        script: flutter packages pub get
        
      # - name: Install CocoaPods
      #   script: |
      #     # なくてもFlutter側でビルドしてくれるが、ここで独立して実行することで、ここの段階のエラーに気づける
      #     # iOSビルドのエラーの8割は pod install 周り（依存関係の競合やバージョン不整合）
      #     find . -name "Podfile" -execdir pod install \;
      - name: Set up code signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles # ← これがないとXcodeに適用されない
          
      # - name: Check 
      #   script: |
      #     # 適用されたか確認（ログで確認できる）
      #     security find-identity -v -p codesigning
      #     # export_options.plistの確認
      #     cat /Users/builder/export_options.plist
      #     # profile
      #     ls ~/Library/MobileDevice/Provisioning\ Profiles/
      #     for f in ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision; do
      #       echo "=== $f entitlements ==="
      #       security cms -D -i "$f" | plutil -extract Entitlements xml1 -o - -
      #     done

      - name: Build IPA for App Store / TestFlight
        script: |
          # pubspec.yamlからバージョン取得
          VERSION=$(grep "^version:" pubspec.yaml | cut -d' ' -f2 | cut -d'+' -f1)
          
          # 1つ目・2つ目の数字を取得
          MAJOR=$(echo $VERSION | cut -d'.' -f1)
          MINOR=$(echo $VERSION | cut -d'.' -f2)
          
          # カスタムエポック（2024-01-01 00:00:00 UTC）からの経過分数
          # → タイムスタンプそのものでなく、後の時刻ほど大きくなる
          CUSTOM_EPOCH=1704067200
          NOW=$(date +%s)
          MINUTES_SINCE_EPOCH=$(( (NOW - CUSTOM_EPOCH) / 180 ))
          
          BUILD_NUMBER="$MAJOR.$MINOR.$MINUTES_SINCE_EPOCH"
          echo "Version:      $VERSION"
          echo "Build number: $BUILD_NUMBER"

          # Codemagicが自動生成したexport_options.plistを使用してIPAをビルド
          flutter build ipa --release \
          --export-options-plist=/Users/builder/export_options.plist \
          --build-name=$VERSION \
          --build-number=$BUILD_NUMBER \
          # --verbose 2>&1 | grep -E "error:|Provisioning|Signing|exportArchive"

    artifacts:
      - build/ios/ipa/*.ipa
      # - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false #App Store Connect にアップロードのみ（内部テスターには配布可能）
        #true だとTestFlight のベータレビューに自動提出