workflows:
  ios-devsigned-build:
    name: iOS Unsigned Build (for AS)
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      # なくても動くが、バージョン固定のために推奨
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    scripts:
      - name: Flutter pub get
        script: flutter packages pub get
        
      - name: Install CocoaPods
        script: |
          # なくてもFlutter側でビルドしてくれるが、ここで独立して実行することで、ここの段階のエラーに気づける
          # iOSビルドのエラーの8割は pod install 周り（依存関係の競合やバージョン不整合）
          find . -name "Podfile" -execdir pod install \;

      - name: Build Unsigned .app
        script: |
          # 1. まず署名なしでビルド
          flutter build ios --release --no-codesign
          
      - name: Payload into .ipa
        script: |
          # 2. .appを手動で.ipaにパッケージングする
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r Runner.ipa Payload
          # 作成場所をCodemagicが認識できる場所に移動
          mv Runner.ipa $CM_BUILD_DIR/Runner.ipa

    artifacts:
      - Runner.ipa