// Mocks generated by Mockito 5.4.6 from annotations
// in portable_sec/test/application/providers/creation_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nfc_toolkit/src/nfc_data.dart' as _i5;
import 'package:nfc_toolkit/src/nfc_service.dart' as _i3;
import 'package:portable_sec/application/providers/creation_state.dart' as _i7;
import 'package:portable_sec/application/services/encryption_service.dart'
    as _i8;
import 'package:portable_sec/domain/value_objects/lock_method.dart' as _i9;
import 'package:portable_sec/domain/value_objects/secret_data.dart' as _i2;
import 'package:portable_sec/infrastructure/repositories/draft_repository_impl.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSecretData_0 extends _i1.SmartFake implements _i2.SecretData {
  _FakeSecretData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NfcService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNfcService extends _i1.Mock implements _i3.NfcService {
  MockNfcService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.NfcData?> get backgroundTagStream =>
      (super.noSuchMethod(
            Invocation.getter(#backgroundTagStream),
            returnValue: _i4.Stream<_i5.NfcData?>.empty(),
          )
          as _i4.Stream<_i5.NfcData?>);

  @override
  _i4.Stream<_i5.NfcError> get errorStream =>
      (super.noSuchMethod(
            Invocation.getter(#errorStream),
            returnValue: _i4.Stream<_i5.NfcError>.empty(),
          )
          as _i4.Stream<_i5.NfcError>);

  @override
  _i4.Future<_i4.Stream<_i3.NfcWriteState>> startWrite(
    List<_i3.NfcWriteData>? dataList, {
    bool? allowOverwrite = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startWrite,
              [dataList],
              {#allowOverwrite: allowOverwrite},
            ),
            returnValue: _i4.Future<_i4.Stream<_i3.NfcWriteState>>.value(
              _i4.Stream<_i3.NfcWriteState>.empty(),
            ),
          )
          as _i4.Future<_i4.Stream<_i3.NfcWriteState>>);

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void resetSession({String? alertMessage}) => super.noSuchMethod(
    Invocation.method(#resetSession, [], {#alertMessage: alertMessage}),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.NfcData?> getInitialTag() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialTag, []),
            returnValue: _i4.Future<_i5.NfcData?>.value(),
          )
          as _i4.Future<_i5.NfcData?>);
}

/// A class which mocks [WizardDraftRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWizardDraftRepository extends _i1.Mock
    implements _i6.WizardDraftRepository {
  MockWizardDraftRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveDraft(_i7.CreationState? state) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [state]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.CreationState?> loadDraft() =>
      (super.noSuchMethod(
            Invocation.method(#loadDraft, []),
            returnValue: _i4.Future<_i7.CreationState?>.value(),
          )
          as _i4.Future<_i7.CreationState?>);

  @override
  _i4.Future<void> deleteDraft() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDraft, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasDraft() =>
      (super.noSuchMethod(
            Invocation.method(#hasDraft, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i8.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<int>> encrypt(_i2.SecretData? data, _i9.LockMethod? lock) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [data, lock]),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<_i2.SecretData> decrypt(
    List<int>? encryptedBytes,
    String? inputSecret,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [encryptedBytes, inputSecret]),
            returnValue: _i4.Future<_i2.SecretData>.value(
              _FakeSecretData_0(
                this,
                Invocation.method(#decrypt, [encryptedBytes, inputSecret]),
              ),
            ),
          )
          as _i4.Future<_i2.SecretData>);
}
